/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BestillingOrderIdRouteImport } from './routes/bestilling.$orderId'
import { Route as AdminKunderRouteImport } from './routes/admin.kunder'
import { Route as AdminKaffeRouteImport } from './routes/admin.kaffe'
import { Route as AdminRunderRoundIdRouteImport } from './routes/admin.runder.$roundId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BestillingOrderIdRoute = BestillingOrderIdRouteImport.update({
  id: '/bestilling/$orderId',
  path: '/bestilling/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminKunderRoute = AdminKunderRouteImport.update({
  id: '/kunder',
  path: '/kunder',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKaffeRoute = AdminKaffeRouteImport.update({
  id: '/kaffe',
  path: '/kaffe',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRunderRoundIdRoute = AdminRunderRoundIdRouteImport.update({
  id: '/runder/$roundId',
  path: '/runder/$roundId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/kaffe': typeof AdminKaffeRoute
  '/admin/kunder': typeof AdminKunderRoute
  '/bestilling/$orderId': typeof BestillingOrderIdRoute
  '/admin/runder/$roundId': typeof AdminRunderRoundIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/kaffe': typeof AdminKaffeRoute
  '/admin/kunder': typeof AdminKunderRoute
  '/bestilling/$orderId': typeof BestillingOrderIdRoute
  '/admin/runder/$roundId': typeof AdminRunderRoundIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/kaffe': typeof AdminKaffeRoute
  '/admin/kunder': typeof AdminKunderRoute
  '/bestilling/$orderId': typeof BestillingOrderIdRoute
  '/admin/runder/$roundId': typeof AdminRunderRoundIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/kaffe'
    | '/admin/kunder'
    | '/bestilling/$orderId'
    | '/admin/runder/$roundId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/kaffe'
    | '/admin/kunder'
    | '/bestilling/$orderId'
    | '/admin/runder/$roundId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/kaffe'
    | '/admin/kunder'
    | '/bestilling/$orderId'
    | '/admin/runder/$roundId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  BestillingOrderIdRoute: typeof BestillingOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestilling/$orderId': {
      id: '/bestilling/$orderId'
      path: '/bestilling/$orderId'
      fullPath: '/bestilling/$orderId'
      preLoaderRoute: typeof BestillingOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/kunder': {
      id: '/admin/kunder'
      path: '/kunder'
      fullPath: '/admin/kunder'
      preLoaderRoute: typeof AdminKunderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kaffe': {
      id: '/admin/kaffe'
      path: '/kaffe'
      fullPath: '/admin/kaffe'
      preLoaderRoute: typeof AdminKaffeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/runder/$roundId': {
      id: '/admin/runder/$roundId'
      path: '/runder/$roundId'
      fullPath: '/admin/runder/$roundId'
      preLoaderRoute: typeof AdminRunderRoundIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminKaffeRoute: typeof AdminKaffeRoute
  AdminKunderRoute: typeof AdminKunderRoute
  AdminRunderRoundIdRoute: typeof AdminRunderRoundIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminKaffeRoute: AdminKaffeRoute,
  AdminKunderRoute: AdminKunderRoute,
  AdminRunderRoundIdRoute: AdminRunderRoundIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  BestillingOrderIdRoute: BestillingOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
